CREATE TABLE TICKET
(
  TICKET_NO INT NOT NULL,
  BUS_REGNO VARCHAR(15) NOT NULL,
  FROM_source VARCHAR(100) NOT NULL,
  TO_destination VARCHAR(100) NOT NULL,
  TIME_OF_ISSUE TIME NOT NULL,
  DATE DATE NOT NULL,
  NUMBER_OF_SEATS INT NOT NULL,
  COST INT NOT NULL,
  --serial_no varchar(10) NOT NULL,
  PRIMARY KEY (TICKET_NO)--,
  --FOREIGN KEY (SERIAL_NO) REFERENCES TICKET_VENDING_MACHINE(SERIAL_NO)
);

CREATE TABLE DEPENDENTS
(
  FNAME VARCHAR(20) NOT NULL,
  MINIT CHAR(1),
  LNAME VARCHAR(20) NOT NULL,
  AGE INT NOT NULL,
  PH_NO CHAR(10) NOT NULL,
  SEX CHAR(1) NOT NULL,
  ADDRESS VARCHAR(400) NOT NULL,
  ESN CHAR(10) NOT NULL,
  CONSTRAINT fk_emp
    FOREIGN KEY (ESN)
    REFERENCES EMPLOYEE(ESN)
    ON DELETE CASCADE
  --ESN CHAR(10) NOT NULL,
  --FOREIGN KEY (ESN) REFERENCES EMPLOYEE(ESN)
);

CREATE TABLE DEPOT
(
  D_ID CHAR(8) NOT NULL,
  LOCATION VARCHAR(100) NOT NULL,
  PH_NO CHAR(10) NOT NULL,
  NO_BUSES INT NOT NULL,
  NO_OF_PLATFORMS INT NOT NULL,
  OPENING_TIME TIME NOT NULL,
  CLOSING_TIME TIME NOT NULL,
  --ESN CHAR(10) NOT NULL,
  PRIMARY KEY (D_ID)--,
  --FOREIGN KEY (ESN) REFERENCES EMPLOYEE(ESN)
);

CREATE TABLE EMPLOYEE
(
  ESN CHAR(10) NOT NULL,
  FNAME VARCHAR(20) NOT NULL,
  MINIT CHAR(1),
  LNAME VARCHAR(20) NOT NULL,
  DOB DATE NOT NULL,
  STREET_NO INT NOT NULL,
  PINCODE CHAR(6) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  PH_NO CHAR(10) NOT NULL,
  SEX CHAR(1) NOT NULL,
  ROLE VARCHAR(40) NOT NULL,
  --D_ID CHAR(8) NOT NULL,
  --STATE VARCHAR(15) NOT NULL,
  --RTO_NO VARCHAR(6) NOT NULL,
  --ESN CHAR(10) NOT NULL,
  PRIMARY KEY (ESN)--,
  --FOREIGN KEY (D_ID) REFERENCES DEPOT(D_ID),
  --FOREIGN KEY (STATE, RTO_NO) REFERENCES BUS(STATE, RTO_NO),
  --FOREIGN KEY (ESN) REFERENCES EMPLOYEE(ESN)
);

CREATE TABLE BUS
(
  STATE VARCHAR(100) NOT NULL,
  RTO_NO VARCHAR(6) NOT NULL,
  INDUCTED_ON DATE NOT NULL,
  MILEAGE INT NOT NULL,
  SERVICE_FREQ INT NOT NULL,
  LAST_SERVICE DATE NOT NULL,
  AC CHAR(1) NOT NULL,
  --ESN CHAR(10) NOT NULL,
  --D_ID CHAR(8) NOT NULL,
  PRIMARY KEY (STATE, RTO_NO)--,
  --FOREIGN KEY (ESN) REFERENCES EMPLOYEE(ESN),
  --FOREIGN KEY (D_ID) REFERENCES DEPOT(D_ID)
);

CREATE TABLE PASSENGER
(
  PASSENGER_ID CHAR(10) NOT NULL,
  AGE_CATEGORY VARCHAR(20) NOT NULL,
  SEX CHAR(1) NOT NULL,
  DISABLED CHAR(1) NOT NULL,
  --STATE VARCHAR(15) NOT NULL,
  --RTO_NO VARCHAR(6) NOT NULL,
  --TICKET_NO INT NOT NULL,
  PRIMARY KEY (PASSENGER_ID)--,
  --FOREIGN KEY (STATE, RTO_NO) REFERENCES BUS(STATE, RTO_NO),
  --FOREIGN KEY (TICKET_NO) REFERENCES TICKET(TICKET_NO)
);

CREATE TABLE ROUTE
(
  ROUTE_NO INT NOT NULL,
  ORIGIN VARCHAR(100) NOT NULL,
  DESTINATION VARCHAR(100) NOT NULL,
  VIA VARCHAR(100) NOT NULL,
  DISTANCE INT NOT NULL,
  NO_OF_BUSES INT NOT NULL,
  EXPENDITURE INT NOT NULL,
  --STATE VARCHAR(15) NOT NULL,
  --RTO_NO VARCHAR(6) NOT NULL,
  PRIMARY KEY (ROUTE_NO)--,
  --FOREIGN KEY (STATE, RTO_NO) REFERENCES BUS(STATE, RTO_NO)
);


CREATE TABLE BUS_ROUTES
(
    STATE VARCHAR(100) NOT NULL,
    RTO_NO VARCHAR(6) NOT NULL,
    ROUTE_1 INT,
    ROUTE_2 INT,
    FOREIGN KEY(STATE,RTO_NO) REFERENCES BUS(STATE,RTO_NO),
    FOREIGN KEY(ROUTE_1) REFERENCES ROUTE(ROUTE_NO),
    FOREIGN KEY(ROUTE_2) REFERENCES ROUTE(ROUTE_NO),
    PRIMARY KEY(STATE,RTO_NO)
);

CREATE TABLE TICKET_VENDING_MACHINE
(
  PRINT_CAPACITY INT NOT NULL,
  TOTAL_AMOUNT INT NOT NULL,
  DATE DATE NOT NULL,
  serial_no varchar(10) NOT NULL,
  --,
  --NewAttribute INT NOT NULL,
  --ESN CHAR(10) NOT NULL,
  PRIMARY KEY (SERIAL_NO)
 -- FOREIGN KEY (ESN) REFERENCES EMPLOYEE(ESN)
);

CREATE TABLE SMART_CARD
(
  SERIAL_NO CHAR(10) NOT NULL,
  OWNER_ID CHAR(10) NOT NULL,
  VALIDITY DATE NOT NULL,
  DATE_OF_ISSUE DATE NOT NULL,
  SCHEME VARCHAR(40) NOT NULL,
  BALANCE INT,
  --ESN CHAR(10) NOT NULL,
  --PASSENGER_ID CHAR(10) NOT NULL,
  PRIMARY KEY (SERIAL_NO),
  --FOREIGN KEY (ESN) REFERENCES EMPLOYEE(ESN),
  --FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID),
  UNIQUE (OWNER_ID)
);

ALTER TABLE TICKET
ADD COLUMN serial_no varchar(10) DEFAULT NULL;
ALTER TABLE TICKET
ADD CONSTRAINT C1 FOREIGN KEY(SERIAL_NO) REFERENCES TICKET_VENDING_MACHINE(SERIAL_NO);

-- ALTER TABLE DEPENDENTS
-- ADD COLUMN ESN CHAR(10) DEFAULT NULL,
-- ADD CONSTRAINT C2 FOREIGN KEY(ESN) REFERENCES EMPLOYEE(ESN);

ALTER TABLE DEPOT
ADD COLUMN MSN CHAR(10) DEFAULT NULL,
ADD CONSTRAINT C3 FOREIGN KEY(MSN) REFERENCES EMPLOYEE(ESN);

ALTER TABLE EMPLOYEE
ADD COLUMN D_ID CHAR(8) DEFAULT NULL,
ADD CONSTRAINT C4 FOREIGN KEY(D_ID) REFERENCES DEPOT(D_ID),
ADD COLUMN STATE VARCHAR(100) DEFAULT NULL ,
ADD COLUMN RTO_NO VARCHAR(6) DEFAULT NULL,
ADD CONSTRAINT C5 FOREIGN KEY(STATE,RTO_NO) REFERENCES BUS(STATE,RTO_NO);
--ADD CONSTRAINT  C6 FOREIGN KEY(ESN) REFERENCES EMPLOYEE(ESN);


ALTER TABLE BUS
ADD COLUMN ESN CHAR(10) DEFAULT NULL,
ADD COLUMN D_ID CHAR(8) DEFAULT NULL,
ADD CONSTRAINT C7 FOREIGN KEY(D_ID) REFERENCES DEPOT(D_ID),
ADD CONSTRAINT C8 FOREIGN KEY(ESN) REFERENCES EMPLOYEE(ESN);

ALTER TABLE PASSENGER
ADD COLUMN STATE VARCHAR(100) DEFAULT NULL,
ADD COLUMN RTO_NO VARCHAR(6) DEFAULT NULL,
ADD COLUMN TICKET_NO INT DEFAULT NULL,
ADD CONSTRAINT C9 FOREIGN KEY(STATE,RTO_NO) REFERENCES BUS(STATE,RTO_NO),
ADD CONSTRAINT C10 FOREIGN KEY(TICKET_NO) REFERENCES TICKET(TICKET_NO);


ALTER TABLE ROUTE
ADD COLUMN STATE VARCHAR(100) DEFAULT NULL,
ADD COLUMN RTO_NO VARCHAR(6) DEFAULT NULL,
ADD CONSTRAINT C11 FOREIGN KEY(STATE,RTO_NO) REFERENCES BUS(STATE,RTO_NO);

ALTER TABLE BUS_ROUTES
ADD COLUMN STATE VARCHAR(100) DEFAULT NULL,
ADD COLUMN RTO_NO VARCHAR(6) DEFAULT NULL,
ADD CONSTRAINT C12 FOREIGN KEY(STATE,RTO_NO) REFERENCES BUS(STATE,RTO_NO);

ALTER TABLE TICKET_VENDING_MACHINE
ADD COLUMN ESN CHAR(10) DEFAULT NULL,
ADD CONSTRAINT C13 FOREIGN KEY(ESN) REFERENCES EMPLOYEE(ESN);

ALTER TABLE SMART_CARD
--ADD COLUMN ESN CHAR(10) DEFAULT NULL,
ADD COLUMN PASSENGER_ID CHAR(10) DEFAULT NULL,
--ADD CONSTRAINT  C14 FOREIGN KEY(ESN) REFERENCES EMPLOYEE(ESN),
ADD CONSTRAINT C15 FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID);


ALTER TABLE EMPLOYEE
ADD COLUMN MSN CHAR(8) DEFAULT NULL,
ADD FOREIGN KEY(MSN) REFERENCES EMPLOYEE(ESN);


CREATE TABLE USERS(
USERNAME VARCHAR(20) NOT NULL,
 PASSWORD VARCHAR(20) NOT NULL,
 EMAIL VARCHAR(40) NOT NULL);

CREATE TABLE ADMIN(
 USERNAME VARCHAR(20) NOT NULL,
 PASSWORD VARCHAR(20) NOT NULL,
 EMAIL VARCHAR(40) NOT NULL);

