UPDATE route SET state = 'KA 04 A' WHERE route_no = 1;
UPDATE route SET state = 'KA 04 A' WHERE route_no = 2;
UPDATE route SET state = 'KA 04 A' WHERE route_no = 3;
UPDATE route SET state = 'KA 04 B' WHERE route_no = 4;
UPDATE route SET state = 'KA 04 B' WHERE route_no = 5;
UPDATE route SET state = 'KA 04 B' WHERE route_no = 6;
UPDATE route SET state = 'KA 04 B' WHERE route_no = 7;
UPDATE route SET state = 'KA 04 C' WHERE route_no = 8;
UPDATE route SET state = 'KA 04 C' WHERE route_no = 9;
UPDATE route SET state = 'KA 04 C' WHERE route_no = 10;
UPDATE route SET state = 'KA 04 D' WHERE route_no = 11;
UPDATE route SET state = 'KA 04 D' WHERE route_no = 12;
UPDATE route SET state = 'KA 04 D' WHERE route_no = 13;
UPDATE route SET state = 'KA 04 D' WHERE route_no = 14;
UPDATE route SET state = 'KA 04 E' WHERE route_no = 15;
UPDATE route SET state = 'KA 04 E' WHERE route_no = 16;
UPDATE route SET state = 'KA 04 E' WHERE route_no = 17;
UPDATE route SET state = 'KA 04 E' WHERE route_no = 18;
UPDATE route SET state = 'KA 04 E' WHERE route_no = 19;
UPDATE route SET state = 'KA 04 E' WHERE route_no = 20;


UPDATE route SET rto_no = '6477' WHERE route_no = 1;
UPDATE route SET rto_no = '6364' WHERE route_no = 2;
UPDATE route SET rto_no = '8307' WHERE route_no = 3;
UPDATE route SET rto_no = '2861' WHERE route_no = 4;
UPDATE route SET rto_no = '6999' WHERE route_no = 5;
UPDATE route SET rto_no = '5686' WHERE route_no = 6;
UPDATE route SET rto_no = '7632' WHERE route_no = 7;
UPDATE route SET rto_no = '5854' WHERE route_no = 8;
UPDATE route SET rto_no = '1588' WHERE route_no = 9;
UPDATE route SET rto_no = '4859' WHERE route_no = 10;
UPDATE route SET rto_no = '6698' WHERE route_no = 11;
UPDATE route SET rto_no = '9775' WHERE route_no = 12;
UPDATE route SET rto_no = '4602' WHERE route_no = 13;
UPDATE route SET rto_no = '6750' WHERE route_no = 14;
UPDATE route SET rto_no = '5630' WHERE route_no = 15;
UPDATE route SET rto_no = '9642' WHERE route_no = 16;
UPDATE route SET rto_no = '3197' WHERE route_no = 17;
UPDATE route SET rto_no = '7264' WHERE route_no = 18;
UPDATE route SET rto_no = '5719' WHERE route_no = 19;
UPDATE route SET rto_no = '3648' WHERE route_no = 20;